### ISSUE TITLE
Tetrahedra labeled as "inside" but are outside

### ISSUE THREAD

**Issue by dyollb** [SCIInstitute/Cleaver2#17] opened 2015-06-02 07:04 UTC
Some months ago I wrote a small code using cleaver 1, which uses implicit functions (spheres) and a constant field for the last field in the volume (what I call outside).

I updated this code for cleaver 2 and find some tetrahedra are labeled as one of the inside sphere domains, but visually they are "clearly" outside the sphere. This looks like a bug, but maybe the problem is related to the constant field I use for the background/outside.

How to reproduce:
https://github.com/SCIInstitute/Cleaver2/pull/16

**Comment by jonbronson** [comment] 2017-07-21 16:57
This bug appears to be caused by numerical instability around certain triple points. I've improved the stability for a certain class of these projections, which should greatly reduce the number of times these are mislabeled. I'm going to close this for now, and we can reopen if the issue reoccurs.

**Closed by jonbronson** 2017-07-21 16:57 UTC
Labels: bug, low-priority
